#tomcat 配置
server:
#  servlet.context-path: /pharmacy-cloud
  port: 8080


spring:
#应用名称
  application:
    name: test-demo
  #日志配置
#  logstash:
#      server: 10.8.76.170
#      port: 5506
#      serviceId: service-yyf-dev
  ##数据库配置数据源

